 * Serving Flask app 'main'
 * Debug mode: off
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5701
[33mPress CTRL+C to quit[0m
[37m[2023-03-04 16:12:34] [INFO]: 当前版本:v1.0.0-rc4 
[0m[37m[2023-03-04 16:12:34] [INFO]: 将使用 device.json 内的设备信息运行Bot. 
[0m[37m[2023-03-04 16:12:34] [INFO]: 密码加密已启用, 请输入Key对密码进行解密以继续: (Enter 提交) 
[0m[37m[2023-03-04 16:12:35] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消. 
[0m[37m[2023-03-04 16:12:40] [INFO]: 开始尝试登录并同步消息... 
[0m[37m[2023-03-04 16:12:40] [INFO]: 使用协议: Android Watch 
[0m[37m[2023-03-04 16:12:42] [INFO]: Protocol -> connect to server: 43.154.240.13:8080 
[0m[33m[2023-03-04 16:12:42] [WARNING]: Protocol -> device lock is disable. http api may fail. 
[0m[37m[2023-03-04 16:12:45] [INFO]: 收到服务器地址更新通知, 根据配置文件已忽略. 
[0m[37m[2023-03-04 16:12:46] [INFO]: 登录成功 欢迎使用: 不瘦十斤不改名字 
[0m[37m[2023-03-04 16:12:46] [INFO]: 开始加载好友列表... 
[0m[37m[2023-03-04 16:12:46] [INFO]: 共加载 9 个好友. 
[0m[37m[2023-03-04 16:12:46] [INFO]: 开始加载群列表... 
[0m[37m[2023-03-04 16:12:50] [INFO]: 共加载 12 个群. 
[0m[37m[2023-03-04 16:12:50] [INFO]: 资源初始化完成, 开始处理信息. 
[0m[37m[2023-03-04 16:12:50] [INFO]: アトリは、高性能ですから! 
[0m[37m[2023-03-04 16:12:50] [INFO]: HTTP POST上报器已启动: http://127.0.0.1:5701/ 
[0m[37m[2023-03-04 16:12:50] [INFO]: CQ HTTP 服务器已启动: 127.0.0.1:5700 
[0m[37m[2023-03-04 16:12:50] [INFO]: 正在检查更新. 
[0m[37m[2023-03-04 16:12:50] [INFO]: 检查更新完成. 当前已运行最新版本. 
[0m[37m[2023-03-04 16:12:50] [INFO]: 开始诊断网络情况 
[0m127.0.0.1 - - [04/Mar/2023 16:12:55] "POST / HTTP/1.1" 200 -
[37m[2023-03-04 16:12:56] [INFO]: 网络诊断完成. 未发现问题 
[0m127.0.0.1 - - [04/Mar/2023 16:13:00] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [04/Mar/2023 16:13:05] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [04/Mar/2023 16:13:10] "POST / HTTP/1.1" 200 -
Exception ignored in: <module 'threading' from '/opt/soft/python3/lib/python3.11/threading.py'>
Traceback (most recent call last):
  File "/opt/soft/python3/lib/python3.11/threading.py", line 1583, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
  File "./main.py", line 13
SyntaxError: Non-ASCII character '\xe7' in file ./main.py on line 13, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
  File "./main.py", line 13
SyntaxError: Non-ASCII character '\xe7' in file ./main.py on line 13, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
